vaadin.launch-browser=true
spring.application.name=trtform

# MySQL Veritabanı Bağlantısı
spring.datasource.url=jdbc:mysql://localhost:3306/trt_survey_db?useSSL=false&serverTimezone=Turkey&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=Kaantemmuz12

# Hibernate / JPA Ayarları
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

